name: Test Setup Scripts
on:
  push:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Batch Setup
        run: .\Sim\gzScripts\setup.bat
        shell: cmd
        
      - name: Test PowerShell Run Script
        run: .\Sim\gzScripts\runGzClassic.ps1 worlds/empty.world
        shell: powershell
        
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Bash Run Script (Syntax Only)
        run: bash -n ./Sim/gzScripts/runGzClassic
